name: Docker Image CI/CD
on:
  push:
    branches: [ master ]
env:
   IMAGE_NAME: ${{ secrets.DOCKER_REPOSITORY }}:v${{ github.run_id }}.${{ github.run_number }}
jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t ${{ env.IMAGE_NAME }} ./
      - name: Login to registry
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }} 
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: registry.cn-shanghai.aliyuncs.com
      - name: Push Image
        run: docker push ${{ env.IMAGE_NAME }}
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker images | grep ${{ secrets.DOCKER_REPOSITORY }} | awk '{print $3}')
            docker rm -f $(docker images | grep ${{ secrets.DOCKER_REPOSITORY }} | awk '{print $3}')
            docker rmi -f $(docker images | grep ${{ secrets.DOCKER_REPOSITORY }} | awk '{print $3}')
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull ${{ env.IMAGE_NAME }}
            docker run -d -p 8000:4000 ${{ env.IMAGE_NAME }}
